indentPreamble: 1
removeTrailingWhitespace: 1
indentRules:
  tabular: "\t"
lookForAlignDelims:
  table: 1
  tabular:
    delimiterRegEx: (?<!\\)(&)(?![^{}]*\})
  tabularx: 1
  longtable: 1
  array: 1
  matrix: 1

verbatimEnvironments:
  nameAsRegex:
    name: '\w+code*?'
    lookForThis: 1

verbatimCommands:
  nameAsRegex: '\w+inline'
  lookForThis: 1

indentAfterItems:
  enumerate: 1
  parts: 1
  equation: 1
  cenum: 1
  mathenum: 1
  penum: 1

itemNames:
  item: 1
  part: 1

specialBeginEnd:
  path:
    begin: '\\path'
    end: ';'
    lookForThis: 1
  specialBeforeCommand: 1
lookForAlignDelims:
  path:
    delimiterRegEx: '(edge|node\h*\{[0-9,A-Z]+\})' 

modifyLineBreaks:
  condenseMultipleBlankLinesInto: 1

replacements:
 - substitution: s/(\{.+)(\\\\)(.+?)(\s*&|\s*\})/\1@@\3\4/gx
   when: before 
 - substitution: s/@@/\\\\/gx
   when: after
