indentPreamble: 1
removeTrailingWhitespace: 1
indentRules:
  tabular: "\t"
lookForAlignDelims:
  table: 1
  tabular:
    delimiterRegEx: (?<!\\)(&)(?![^{}]*\})
  tabularx: 1
  longtable: 1
  array: 1
  matrix: 1

verbatimEnvironments:
  texlst: 1
  shellcmd: 1
  cpplst: 1

indentAfterItems:
  enumerate: 1
  parts: 1
  equation: 1
  cenum: 1
  mathenum: 1
  penum: 1

itemNames:
  item: 1
  part: 1

specialBeginEnd:
  path:
    begin: '\\path'
    end: ';'
    lookForThis: 1
  specialBeforeCommand: 1
lookForAlignDelims:
  path:
    delimiterRegEx: '(edge|node\h*\{[0-9,A-Z]+\})' 
